PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(DISTINCT ?person) AS ?total) WHERE {
  ?type rdfs:subClassOf* gndo:Person .
  ?person a ?type .

  ?person gndo:professionOrOccupation ?occ .
  ?occ gndo:preferredNameForTheSubjectHeading ?occLabel .
  FILTER(REGEX(LCASE(STR(?occLabel)),
    "bischof|abt|kanoniker|domherr|geistlich|propst|diakon|erzbischof|prior|pfarrer|kleriker|dekan|kustos|scholast|kantor"
  ))
}
